services:
    nginx:
        image: pair-matching-game
        ports:
            - "8090:80"
        restart: always
        depends_on:
            - myserver
        container_name: pair-matching-game
    myserver:
        image: pair-matching-server
        ports:
            - "8085:80"
        container_name: pair-matching_server
