
services:
    nginx:
        image: projectfront/pairmatchingnginx
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - expressserver
        container_name: pairmatching_nginx
        # extra_hosts:
        # - "host.docker.internal:host-gateway"
    expressserver:
        image: projectfront/pairmatchingserver
        ports:
            - "9000:9000"
        container_name: pairmatching_server
